spring:
  application:
    name: eva-social

  datasource:
    url: jdbc:mysql://localhost:3306/eva-social?createDatabaseIfNotExist=true
    username: matt
    password: Gudmord92!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# JWT Configuration
jwt:
  secret: REPLACE_WITH_GENERATED_BASE64_SECRET_AT_LEAST_256_BITS
