spring:
  application:
    name: eva-social

  datasource:
    url: jdbc:mysql://localhost:3306/eva-social?createDatabaseIfNotExist=true
    username: matt
    password: Gudmord92!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  # Jackson configuration to handle null values in boolean fields
  jackson:
    deserialization:
      fail-on-null-for-primitives: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:7s1YRg86WGmRHqniBez5bNdmS+GNteG9OZRSV9XafuA=}
